name: Deploy to DEV with Status

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Render DEV
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deploy Hook
        run: |
          echo "Triggering deployment via Render Deploy Hook..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

      - name: Poll Render Deployment Status
        run: |
          echo "Polling Render deployment status..."

          for i in {1..30}
          do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" https://api.render.com/v1/services/srv-d1ll4cur433s73drskdg/deploys)
            echo "Response: $response"  # Optional: comment this out after confirming it works
            status=$(echo "$response" | jq -r '.[0].status')
            echo "Current deploy status: $status"

            if [ "$status" = "live" ]; then
              echo "✅ Deployment is live!"
              exit 0
            elif [ "$status" = "failed" ]; then
              echo "❌ Deployment failed!"
              exit 1
            fi
            sleep 10
          done

          echo "⚠️ Deployment did not complete in time."
          exit 1
          
