name: Deploy to DEV with Status

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Render DEV
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        run: |
          echo "🚀 Triggering Render deployment..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

      - name: Wait for App to Become Healthy
        run: |
          echo "⏳ Waiting for service to become healthy at /health..."
          MAX_RETRIES=50
          SLEEP_SECONDS=30
          URL="https://sanalink-api.onrender.com/api/Health"

          for i in $(seq 1 $MAX_RETRIES); do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            echo "Attempt $i: Status $STATUS"
            if [ "$STATUS" -eq 200 ]; then
              echo "✅ Service is live and healthy!"
              exit 0
            fi
            echo "Waiting ${SLEEP_SECONDS}s before retrying..."
            sleep $SLEEP_SECONDS
          done

          echo "❌ Service did not become healthy after $((MAX_RETRIES * SLEEP_SECONDS / 60)) minutes."
          exit 1
